import { PanelModel } from '../webModels/Panel.model';
import { ToolConnectionModel } from '../webModels/ToolConnection.model';
import { CommunicationChannelDataModel } from '../webModels/CommunicationChannelData.model';
import { SureSENSInterfaceCardDataModel } from '../webModels/SureSENSInterfaceCardData.model';
import { UnitSystemModel } from '../webModels/UnitSystem.model';
import { DataPointLinearScaleConversionModel } from '../webModels/DataPointLinearScaleConversion.model';
import { ModbusConfigurationModelUI } from '../webModels/ModbusConfigurationModelUI.model';
import { DeleteObjectDataModel } from '../webModels/DeleteObjectData.model';
import { ModbusConfigurationChannelModels } from '../webModels/ModbusConfigurationChannelModels.model';
import { InterfaceCardChannelModels } from '../webModels/InterfaceCardChannelModels.model';
import { InforceDeviceDataModel } from '../webModels/InforceDeviceData.model';
import { AlarmDefinitionDataUIModel } from '../webModels/AlarmDefinitionDataUI.model';
import { ErrorHandlingUIModel } from '../webModels/ErrorHandlingUI.model';
import { LoginModel } from '../webModels/Login.model';
import { PanelConfigurationModel } from '../webModels/PanelConfiguration.model';
import { UnitSystemUIModel } from './unit-system.model';
import { DataSourceUIModel } from '../UIModels/dataSource.model';
import { PanelConfigurationCommonModel } from '../webModels/PanelConfigurationCommon.model';
import { PublishingDataUIModel } from './dataPublishing.model';
import { InchargeWellUIModel } from './Incharge.well.model';
import { ModbusMapTemplateUIModel } from './modbusTemplate.model';
import { ToolConnectionUIModel } from './tool-connection.model';
import { SureFLOFlowMeterUIModel } from './sureflo.model';
import { ShiftDefaultUIModel } from './shift-default.model';
import { AlarmsAndLimitsUIModel, PanelDefaultUIModel } from './panel-default.model';
import { DataLoggerUIModel } from './dataLogger.model';
import { DataLoggerTypesDataModel } from './dataLoggerTypes.model';
import { DiagnosticsTestTypesDataModel } from './diagnosticsTestTypes.model';
import { SieUIModel } from './sie.model';
import { eFCVPositionUIModel } from './eFCVPosition.model';
import { MultiNodePositionDefaultsDataUIModel } from './MultiNodePositionDefaultsDataUI.model';

export class ConfigurationDataModel {

    public constructor() {
        this.VersionNumber = '';
        this.panelConfigurationCommon = null;
        this.errorHandlingSettings = null;
        this.unitSystem = null;
        this.shiftDefaults = null;
        this.panelDefaults = null;
        this.wells = [];
        this.dataSources = [];
        this.toolConnections = [];
        this.publishing = [];
        this.customMaps = [];
        this.sureflo = [];
        this.Alarms = [];
        this.dataLoggers = [];
        this.dataLoggerTypes = [];
        this.sies = [];
        this.diagnosticsTestTypes = [];
        this.eFCVPositionSettings = null;
    }
    public VersionNumber: string;
    public panelConfigurationCommon: PanelConfigurationCommonModel;
    public wells: InchargeWellUIModel[];
    public dataSources: DataSourceUIModel[];
    public toolConnections: ToolConnectionUIModel[];
    public errorHandlingSettings: ErrorHandlingUIModel;
    public unitSystem: UnitSystemModel;
    // do not export user account
    public users: LoginModel[];
    public publishing: PublishingDataUIModel[];
    public customMaps: ModbusMapTemplateUIModel[];
    public sureflo: SureFLOFlowMeterUIModel[];
    shiftDefaults: ShiftDefaultUIModel;
    panelDefaults: PanelDefaultUIModel;
    alarmsAndLimits: AlarmsAndLimitsUIModel;
    // public Panel: PanelModel;
    // public ToolConnections: ToolConnectionModel[];
    // public CommunicationChannels: CommunicationChannelDataModel[];
    // public ModbusConfigurations: any;
    // public SureSENSInterfaceCardData: SureSENSInterfaceCardDataModel[];
    // public UnitSystem: UnitSystemModel;
    // public UnitSystems: UnitSystemModel[];
    // public DataPointLinearScaleConversion: DataPointLinearScaleConversionModel[];
    // public ModbusConfigurationsArrayUI: ModbusConfigurationModelUI[];
    // public ErrorHandlings: ErrorHandlingUIModel[];
    // public DeleteObjects: DeleteObjectDataModel[];
    // public ModbusConfigurationChannels: ModbusConfigurationChannelModels;
    // public InterfaceCardChannels: InterfaceCardChannelModels;
    // public InforceDevices: InforceDeviceDataModel[];
    // public IsImport: boolean;
    public Alarms: AlarmDefinitionDataUIModel[];
    public dataLoggers: DataLoggerUIModel[];
    public dataLoggerTypes: DataLoggerTypesDataModel[];
    public diagnosticsTestTypes: DiagnosticsTestTypesDataModel[];
    public sies: SieUIModel[];
    public eFCVPositionSettings: MultiNodePositionDefaultsDataUIModel;
}
